PACKAGE_NAME=xt-rts
pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null
PACKAGE_VERSION=$(./version.sh)
popd >/dev/null
BUILT_MODULE_NAME[0]=xt_RTS
DEST_MODULE_LOCATION[0]=/kernel/extra
STRIP[0]=no
MAKE[0]="make xt_RTS.ko KCFLAGS=-O3"
PRE_BUILD="./configure --from-dkms-conf=$kernel_source_dir"
AUTOINSTALL=yes
